### ISSUE TITLE
Attirube error

### ISSUE THREAD

**Issue by rd15armas** [funoverip/gr-cc1111#4]
Hİ, I've geting this error on gnuradio V3.7.1. Could you please help me..?

Traceback (most recent call last):
  File "/home/hp/gr-cc1111/grc/grc_cc1111_hackrf_sender.py", line 129, in <module>
    main()
  File "/home/hp/gr-cc1111/grc/grc_cc1111_hackrf_sender.py", line 118, in main
    tb = top_block_cls()
  File "/home/hp/gr-cc1111/grc/grc_cc1111_hackrf_sender.py", line 55, in __init__
    source_queue=myqueue_in
  File "/usr/local/lib/python2.7/dist-packages/cc1111/cc1111_packet.py", line 139, in __init__
    gr.io_signature(1, 1, packet_source._hb.output_signature().sizeof_stream_item(0)) # Output signature
  File "/usr/lib/python2.7/dist-packages/gnuradio/gr/hier_block2.py", line 92, in __getattr__
    return getattr(self._impl, name)
AttributeError: 'hier_block2_sptr' object has no attribute '_hb'

**Comment by funoverip** [comment]
Hi,

I have honestly no idea where does it come from but, issue #1 was similar, and the reporter had to apply a GNURadio patch. Seems to be related to your GR version. If you find more details, please let me know !

Regards.
